name: podcasts_ofw_admin
description: Admin panel for OFW Podcasts

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  provider: ^6.1.1
  fluttertoast: ^9.0.0
  supabase: ^2.10.0  # Add this for Supabase
  just_audio: ^0.10.5
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true